<a href="https://colab.research.google.com/github/susanaes/topicos_ciencia_datos/blob/Trabajo_Tarea1/Tarea_1_capitulo_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En base a los códigos que estan en el capitulo 8:

https://github.com/ricardo-rios/topicos_ciencia_datos/tree/master/unidad_ii/intro_ml/chapter8

Desarrollar un código en google colab (Notebook) que permita hacer una selección de variables del siguiente dataset:

https://raw.githubusercontent.com/ricardo-rios/topicos_ciencia_datos/master/tareas/tarea0001/datos0001.csv

Los nombres de las variables estan en la primera fila. Los predictores son X1, X2, ..., X25 y la variable a predecir (target) es Y. Enviar el código en formato ipynb a más tardar poco antes de la medianoche del 10 de Octubre por la plataforma google classroom.

## Feature_importance 





### **Feature Importance with Extra Trees Classifier**





In [1]:
from pandas import read_csv
from sklearn.ensemble import ExtraTreesClassifier

In [10]:
url = "https://raw.githubusercontent.com/susanaes/topicos_ciencia_datos/master/tareas/tarea0001/datos0001.csv"

dataframe = read_csv(url)

# separate array into input and output components
X = dataframe.iloc[:,0:25]
Y = dataframe.iloc[:,25]

In [8]:
dataframe.head()

X1        X2        X3        X4  ...       X23       X24       X25  Y
0  0.099427  0.757122  0.347820 -1.070386  ...  2.010244  0.640326 -0.696634  0
1  0.324543 -0.260349 -0.692412 -1.098060  ... -2.038009  1.653168  0.755058  0
2 -0.189937  0.402457  0.089148  0.054241  ...  2.228478  1.636842 -0.630777  0
3 -1.213477 -1.076779 -0.361017 -0.572703  ... -2.816330  0.432327  1.355193  1
4 -0.006235 -0.368401  0.212226 -0.839388  ...  3.500016  0.015047  0.077092  1

[5 rows x 26 columns]

In [9]:
X.head()

X1        X2        X3  ...       X23       X24       X25
0  0.099427  0.757122  0.347820  ...  2.010244  0.640326 -0.696634
1  0.324543 -0.260349 -0.692412  ... -2.038009  1.653168  0.755058
2 -0.189937  0.402457  0.089148  ...  2.228478  1.636842 -0.630777
3 -1.213477 -1.076779 -0.361017  ... -2.816330  0.432327  1.355193
4 -0.006235 -0.368401  0.212226  ...  3.500016  0.015047  0.077092

[5 rows x 25 columns]

In [11]:
Y.head()

0    0
1    0
2    0
3    1
4    1
Name: Y, dtype: int64

In [12]:
# feature extraction
model = ExtraTreesClassifier(n_estimators=100)
model.fit(X, Y)
print(model.feature_importances_)

[0.00786084 0.00776475 0.00770137 0.0074824  0.00729896 0.00758739
 0.00789984 0.00753446 0.08292478 0.10761162 0.02682898 0.02990167
 0.08790782 0.04079596 0.12128759 0.02599028 0.02368471 0.05406087
 0.00792833 0.22121994 0.00794869 0.00752571 0.07822065 0.00756582
 0.00746656]


## PCA

### **Feature Extraction with PCA**

In [13]:
from sklearn.decomposition import PCA

In [14]:
# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(X)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [0.33817049 0.13694106 0.08991985]
[[-1.93391051e-03  1.56247828e-07  1.08084160e-03 -2.24978732e-03
  -4.70644400e-04  2.45602263e-03  4.85349200e-04  2.32985698e-04
  -1.11900477e-01  9.53978410e-02  7.89416582e-02 -2.95579847e-01
  -2.22160351e-01  2.24013112e-01  1.06789730e-01  1.15035413e-01
   4.18108831e-01  7.48161586e-01  5.24238689e-04 -9.16017226e-02
  -1.08219878e-04  4.51082499e-04 -1.32792713e-01 -1.04866757e-03
   6.15182865e-04]
 [-2.61873839e-03 -4.36490115e-03 -1.97315086e-03 -1.38693006e-03
  -5.88584619e-04  5.68961048e-04 -3.02006149e-03  1.50067356e-03
   3.52416100e-01 -1.26871312e-01  1.46570123e-01  9.62652243e-02
  -1.58265507e-01 -2.78493386e-01 -1.74638112e-01  2.30536557e-01
   6.94405005e-01 -2.31763719e-01 -1.50289675e-03 -1.21306890e-01
   9.42291586e-04 -6.06421281e-03  3.03280103e-01  3.74139361e-03
   2.31707283e-04]
 [-1.14172331e-02  1.73396283e-03 -1.73440458e-03  9.59556101e-04
   2.75368502e-03  2.04239450e-03  3.67583359e-04

## Recursive_feature_elimination

### **Feature Selection with RFE**


In [15]:

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [16]:
# feature extraction
model = LogisticRegression(solver='liblinear')
rfe = RFE(model, 3)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 3
Selected Features: [False False False False False False False False False  True False False
  True False False False False False False  True False False False False
 False]
Feature Ranking: [19 13 16 18 23 17 11 14  4  1  6  8  1  5  3  7 21  9 15  1 20 22  2 10
 12]


## univariate_selection

### **Feature Selection with Univariate Statistical Tests**

In [17]:
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [18]:
# feature extraction
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)

In [19]:
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)

[2.315e+00 1.009e-01 1.473e-01 5.567e-06 1.957e-03 1.104e+00 1.757e-01
 9.235e-02 1.090e+03 1.259e+03 3.867e+00 6.147e-03 1.261e+03 2.556e-03
 1.359e+03 1.056e-01 1.230e+02 2.373e+02 6.973e-01 7.100e+03 1.842e+00
 2.941e-02 1.303e+03 1.871e+00 1.431e+00]


In [20]:
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[[-0.438  1.562 -1.144  2.01 ]
 [-0.098  2.3   -3.202 -2.038]
 [-0.056  3.922  0.232  2.228]
 [-1.585  0.129  2.516 -2.816]
 [-0.574 -0.357  2.457  3.5  ]]
